### ISSUE TITLE
Implementation of negative tags

### ISSUE THREAD

**Issue by sashaok123** [xinyu1205/Recognize_Anything-Tag2Text#12]
Hi, is there any way to embed negative tags in the project?
These tags should work the opposite of the usual ones, that is, what will be indicated as a negative tag will be ignored in the description of the images.

I made myself a mini GUI and would like to add negative tags to it, but I don't know if it's really possible to pull it off.
![image](https://github.com/xinyu1205/Recognize_Anything-Tag2Text/assets/27728380/52d7e105-a447-4e65-a806-eb359cee3f60)

**Comment by xinyu1205** [comment]
Hi, sorry for the delay in responding due to my busy schedule.
Currently, Tag2Text does not support negative tags, but I think you propose a very good application scenario for Tag2Text. In my opinion, the key to implementing negative tags is to build a dataset so that when training the image-tag-text generation task, the input tags are not positive tags but completely opposite negative tags. Training or fine-tuning Tag2Text with such a dataset should result in negative tags works. By the way, we will open source Tag2Text training code within a few weeks at the last.
Best wishes!
